openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Shipment API"
  description: "API for listing and retrieving shipments."

paths:
  /shipments/:
    get:
      tags:
        - Shipments
      summary: List shipments
      operationId: listShipments
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
        - name: page_size
          in: query
          description: Number of items to return per page for pagination
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                  previous:
                    type: string
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/ListShipment"
        "400":
          description: Bad request
        "404":
          description: Not found

  /shipments/{carrier}/{tracking_number}/:
    get:
      tags:
        - Shipments
      summary: Retrieve shipment details
      operationId: retrieveShipment
      parameters:
        - name: carrier
          in: path
          description: Name of the carrier
          required: true
          schema:
            type: string
        - name: tracking_number
          in: path
          description: Tracking number of the shipment
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetrieveShipment"
        "400":
          description: Bad request
        "404":
          description: Not found

components:
  schemas:
    Address:
      type: object
      properties:
        id:
          type: integer
        country:
          type: string
        details:
          type: string
        zipcode:
          type: string
        city:
          type: string
        location:
          type: object
          nullable: true
          properties:
            lat:
              type: number
            lon:
              type: number

    Article:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        price:
          type: number
        sku:
          type: string
        shipment:
          type: integer

    Weather:
      type: object
      properties:
        id:
          type: integer
        main:
          type: string
        description:
          type: string
        icon:
          type: string

    ListShipment:
      type: object
      properties:
        id:
          type: integer
        tracking_number:
          type: string
        sender_address:
          $ref: "#/components/schemas/Address"
        receiver_address:
          $ref: "#/components/schemas/Address"
        status:
          type: string
        carrier:
          type: string

    RetrieveShipment:
      type: object
      properties:
        id:
          type: integer
        tracking_number:
          type: string
        sender_address:
          $ref: "#/components/schemas/Address"
        receiver_address:
          $ref: "#/components/schemas/Address"
        status:
          type: string
        carrier:
          type: string
        articles:
          type: array
          items:
            $ref: "#/components/schemas/Article"
        weather:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Weather"
